version: '3'
services:
  websocket:
    container_name: websocket
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis-server:
    image: "redis:alpine"
    ports:
      - "6380:6379"