version: '3'
services:
  websocket:
    container_name: websocket
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6380:6379"
  redis-session:
    container_name: redis-session
    image: "redis:alpine"
    ports:
      - "6381:6379"
  redis-insight:
    container_name: redis-insight
    image: "redislabs/redisinsight:latest"
    ports:
      - "8001:8001"    
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
      